# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: labext-template
author_email: ivycong_1986@163.com
author_name: Wing S C Chen
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab Hello world extension.
python_name: jupyterlab_apod
repository: https://github.com/DaWingChan/jupyterlab-extension
test: true
viewer_name: ''

